config/routes.rb
  Rails.application.routes.draw do

  root to: 'pages#home'


  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :posts, only: [:show, :index]

  resources :categories, only: [:show, :index]

  resources :strategies, :path => 'strategy', only: [:show, :index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @posts = Post.all
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def contact
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  def index
    @posts = Post.all.where(category: "Strategy")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/views/categories/index.html.erb
<h1>Categories#categories</h1>
<p>Find me in app/views/categories/index.html.erb</p>

<div>
<%= link_to strategies_path, class: 'card-link' do %>
  <h3>Strategy</h3>
  <p> This category encompasses x, y and z</p>
<% end %>
</div>
  <h3>Tactics</h3>
  <h3>Analytics</h3>
  <h3>Technical</h3>
  <h3>Tools</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Growaking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<p>I already changed something</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<p>Now is <%= Time.now %><p>

<p>Now is 20XX-XX-XX XX:XX:XX +0000</p>

<% Post.all.reverse.each do |post| %>
  <h3><%= post.title %> </h3>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<p>I already changed something</p>


<% @posts.reverse.each do |post| %>
  <h3><%= post.title %> </h3>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>
<p>I already changed something</p>

<h3><%= @post.title %> </h3>
<h3><%= @post.category %> </h3>

app/views/strategies/index.html.erb
<h1>Strategies#strategy</h1>
<p>Find me in app/views/strategies/strategy.html.erb</p>

<% @posts.reverse.each do |post| %>
  <%= link_to post_path(post), class: 'card-link' do %>
    <h3><%= post.id %> </h3>
    <h3><%= post.category %> </h3>
  <% end %>
<% end %>